#!/usr/bin/env perl
use Dzpl
    name => 'Test-t',
    version => '0.0031',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        File::Spec
        Test::More
        Test::Most
    /;
;

{ plugin '@ROKR' }
