#!/usr/bin/env perl
use Dzpl
    name => 'Test-t',
    version => '0.003',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        File::Spec
        Test::More
        Test::Most
    /;
;

plugin
    '@Basic' => qr/Readme$/,
    'PkgVersion',
    'PodWeaver',
    'ReadmeFromPod',
    '=Dist::Dzpl::Plugin::DynamicManifest',
    '=Dist::Dzpl::Plugin::CopyReadmeFromBuild',
;

run;


